# Copyright 2025 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: IREE Sharktank Models Tests

inputs:
  SKU:
    description: "Type of SKU to test"
    required: true
  CHIP:
    description: "Type of chip to use"
    required: true
  VENV_DIR:
    description: "Path to the virtual environment"

runs:
  using: "composite"
  steps:
    - name: Checkout repository 
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2 
      with:
        clean: false # doesn't clean up the venv created before this composite action
    
    - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
      with:
        python-version: "3.11"

    - name: Setting up virtual environment and install Python dependencies
      shell: bash
      run: |
        source ${{ inputs.VENV_DIR }}/bin/activate
        pip install -e ${GITHUB_ACTION_PATH}/sharktank_models
        pip install -r ${GITHUB_ACTION_PATH}/sharktank_models/requirements-iree.txt
    
    - name: Run compilation and quality tests
      shell: bash
      run: |
        source ${{ inputs.VENV_DIR }}/bin/activate
        python ${GITHUB_ACTION_PATH}/sharktank_models/regression_tests/run_quality_tests.py \
          --model=${{ inputs.model }} \
          --sku=${{ inputs.sku }} \
          --backend=${{ inputs.backend }}
    
      # Using bash conditionals because if statements in composite actions are not yet supported: https://github.com/actions/runner/blob/main/docs/adrs/0549-composite-run-steps.md#if-condition
    - name: Run benchmark tests
      shell: bash
      run: |
        source ${{ inputs.VENV_DIR }}/bin/activate
        case ${{ inputs.run_benchmarks }} in
          (true)
            echo "Benchmark flag selected, running benchmark tests..."
            python ${GITHUB_ACTION_PATH}/sharktank_models/benchmarks/run_benchmarks.py \
              --model=${{ inputs.model }} \
              --sku=${{ inputs.sku }} \
              --backend=${{ inputs.backend }}
            echo "$(<job_summary.md )" >> $GITHUB_STEP_SUMMARY
            rm job_summary.md job_summary.json
            ;;
          (false)
            echo "Benchmark flag not selected, skipping benchmark tests..."
            ;;
        esac
