# Copyright 2025 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: IREE Sharktank Models Tests

inputs:
  MATRIX_NAME:
    description: "Unique identifier for matrix run name" # (ex: amdgpu_rocm_mi300_gfx942_regression)
  SKU:
    description: "SKU target for the quality and benchmark tests" # (ex: mi300)
  CHIP:
    description: "The rocm chip for the quality and benchmark tests" # (ex: gfx942)
  VENV_DIR:
    description: "Path to the Python virtual environment directory" # (ex: /home/venv)
  TARGET:
    description: "Target type for the sharktank model tests" # (ex: target_gpu)
  GPU:
    description: "Type of GPU for the sharktank model tests" # (ex: gfx1100)
  BACKEND:
    description: "Type of backend for the quality and benchmark tests" # (ex: rocm)
  EXTERNAL_TEST_FILE_DIRECTORY:
    # Any additional external files needed for testing can be added in this directory (ex: attention_spec.mlir)
    description: "(Optional) The directory of external test configurations for quality and benchmark tests" # (ex: /files/external_test_files/)
  QUALITY_TEST_DIRECTORY:
    # Model JSON configurations are placed in this directory. For an example, see /sharktank_models/quality_tests/sdxl/clip_rocm.json
    description: "The directory of JSON test configurations for quality tests" # (ex: /quality_test_files/sdxl)
  BENCHMARK_TEST_DIRECTORY:
    # Model JSON configurations are placed in this directory. For an example, see /sharktank_models/benchmarks/sdxl/clip_rocm.json
    description: "The directory of JSON test configurations for benchmark tests" # (ex: /benchmark_files/sdxl)
  IREE_TEST_FILES:
    # Existing inputs, outputs, weights and mlir files are placed in this directory, to speed up test runs with caching
    description: "(Optional) Directory of the iree test files for quality and benchmark tests" # (ex: /iree_test_files)

runs:
  using: "composite"
  steps:
    # Pulling IREE Test Suites specifically for Git LFS files
    - name: Checkout IREE Test Suites repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2 
      with:
        repository: iree-org/iree-test-suites
        path: iree-test-suites
        lfs: true

    - name: Pull Git LFS objects
      shell: bash
      run: |
        git lfs install
        git lfs pull

    - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
      with:
        python-version: "3.11"

    - name: Setting up virtual environment and install Python dependencies
      shell: bash
      run: |
        source ${{ inputs.VENV_DIR }}/bin/activate
        pip install -e ${GITHUB_ACTION_PATH}
        pip install -r ${GITHUB_ACTION_PATH}/requirements-iree.txt
      env:
        IREE_TEST_FILES: ${{ inputs.IREE_TEST_FILES }}
    
    - name: Run sharktank specific model tests
      shell: bash
      if: contains(inputs.MATRIX_NAME, 'model')
      run: |
        source ${{ inputs.VENV_DIR }}/bin/activate
        pytest ${GITHUB_ACTION_PATH} \
            -rA \
            --log-cli-level=info \
            --override-ini=xfail_strict=false \
            -m ${{ inputs.TARGET }} \
            --timeout=120 \
            --durations=0 \
            --ignore=${GITHUB_ACTION_PATH}/benchmarks \
            --ignore=${GITHUB_ACTION_PATH}/quality_tests
      env:
        HIP_TARGET: ${{ inputs.GPU }}
        ASSET_PATH: ${{ github.workspace }}/iree-test-suites/sharktank_models

    - name: Run regression quality tests
      shell: bash
      if: contains(inputs.MATRIX_NAME, 'regression')
      run: |
        source ${{ inputs.VENV_DIR }}/bin/activate
        pytest \
          ${GITHUB_ACTION_PATH}/quality_tests \
          -rpFe \
          --log-cli-level=info \
          --durations=0 \
          --timeout=1200 \
          --capture=no \
          --test-file-directory=${{ inputs.QUALITY_TEST_DIRECTORY }} \
          --external-file-directory=${{ inputs.EXTERNAL_TEST_FILE_DIRECTORY }}
      env:
        ROCM_CHIP: ${{ inputs.CHIP }}
        SKU: ${{ inputs.SKU }}
        IREE_TEST_FILES: ${{ inputs.IREE_TEST_FILES }}
        BACKEND: ${{ inputs.BACKEND }}

    # Since the benchmark tests require compiled model files, this step must run after the quality tests
    - name: Run regression benchmark tests
      shell: bash
      if: contains(inputs.MATRIX_NAME, 'regression')
      run: |
        source ${{ inputs.VENV_DIR }}/bin/activate
        pytest \
          ${GITHUB_ACTION_PATH}/benchmarks \
          --log-cli-level=info \
          --retries=7 \
          --timeout=600 \
          --test-file-directory=${{ inputs.BENCHMARK_TEST_DIRECTORY }} \
          --external-file-directory=${{ inputs.EXTERNAL_TEST_FILE_DIRECTORY }}
          
        echo "$(<${GITHUB_ACTION_PATH}/job_summary.md )" >> $GITHUB_STEP_SUMMARY
      env:
        ROCM_CHIP: ${{ inputs.CHIP }}
        SKU: ${{ inputs.SKU }}
        IREE_TEST_FILES: ${{ inputs.IREE_TEST_FILES }}
        BACKEND: ${{ inputs.BACKEND }}
        JOB_SUMMARY_PATH: ${GITHUB_ACTION_PATH}
